// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8IdHs6fRL5-Rt9QTggSjSP4kCVBOf_g',
    appId: '1:361762167299:web:7e12f5a20f983f7abb8c36',
    messagingSenderId: '361762167299',
    projectId: 'paralex-staging',
    authDomain: 'paralex-staging.firebaseapp.com',
    storageBucket: 'paralex-staging.firebasestorage.app',
    measurementId: 'G-SNYCVJZ4ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11ZXQ1zK1_i7-gpf3VhkVnmN-lKO9EAE',
    appId: '1:361762167299:android:37de52ffaec2a72abb8c36',
    messagingSenderId: '361762167299',
    projectId: 'paralex-staging',
    storageBucket: 'paralex-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_anJS-SD691uoYJEIyEQeo3DjUZ3RqY',
    appId: '1:361762167299:ios:d1d13a38d9b383f5bb8c36',
    messagingSenderId: '361762167299',
    projectId: 'paralex-staging',
    storageBucket: 'paralex-staging.firebasestorage.app',
    iosClientId: '361762167299-lgk4k7nljjpkhv4hrlpah2rkb02se8tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.paralax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl_anJS-SD691uoYJEIyEQeo3DjUZ3RqY',
    appId: '1:361762167299:ios:d1d13a38d9b383f5bb8c36',
    messagingSenderId: '361762167299',
    projectId: 'paralex-staging',
    storageBucket: 'paralex-staging.firebasestorage.app',
    iosClientId: '361762167299-lgk4k7nljjpkhv4hrlpah2rkb02se8tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.paralax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8IdHs6fRL5-Rt9QTggSjSP4kCVBOf_g',
    appId: '1:361762167299:web:945895bff62eeb99bb8c36',
    messagingSenderId: '361762167299',
    projectId: 'paralex-staging',
    authDomain: 'paralex-staging.firebaseapp.com',
    storageBucket: 'paralex-staging.firebasestorage.app',
    measurementId: 'G-6HRTHTNVFY',
  );
}
