name: paralex
description: "Logistics and Legal App."
publish_to: "none"
##version: 0.1.0
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^2.0.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  iconsax_flutter: ^1.0.0
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
