name: paralex
description: "Logistics and Legal App."
publish_to: "none"
##version: 0.1.0
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^2.0.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^5.0.0
  iconsax_flutter: ^1.0.0
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
#  flutter_sound: ^9.17.0
  flutter_sound: ^9.3.1
  permission_handler: ^11.3.1
  file_picker: ^8.1.4
  ffmpeg_kit_flutter: ^6.0.3
  shared_preferences: ^2.3.3
  google_maps_flutter: ^2.10.0
#  geolocator: ^13.0.2
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.2
#  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
