name: paralex
description: "Logistics and Legal App."
publish_to: "none"
##version: 0.1.0
version: 1.1.1+12

environment:
  sdk: ^3.5.1

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^2.0.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  iconsax_flutter: ^1.0.0
  intl: ^0.20.1
  intl_phone_field: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  badges: ^3.1.2
#  flutter_sound: ^9.17.0
  flutter_sound: ^9.3.1
  permission_handler: ^11.3.1
  file_picker: ^8.1.4

#  ffmpeg_kit_flutter_full: ^5.1.0
  shared_preferences: ^2.3.3
  google_maps_flutter: ^2.10.0
#  geolocator: ^13.0.2
  flutter_typeahead:
  geocoding: ^3.0.0
  geolocator: ^13.0.2
#  geocoding: ^2.0.5

  fl_chart: ^0.69.2
  dio: ^5.1.2
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5

  path_provider: any
  path: any
  http: any
  media_kit: ^1.1.11
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # Path to your icon
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  ios_icon_size: 80
  # Android adaptive background
#  adaptive_icon_foreground: "assets/icons/icon_foreground.png"  # Optional

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
